// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoi2z_zZGTE7Yb1hoUIEeyGhGUnLYUOl4',
    appId: '1:691493604455:web:29e309830dfb3d1cf8d8c2',
    messagingSenderId: '691493604455',
    projectId: 'j2062-2dd01',
    authDomain: 'j2062-2dd01.firebaseapp.com',
    databaseURL:
        'https://j2062-2dd01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'j2062-2dd01.firebasestorage.app',
    measurementId: 'G-5YVG2TWDSL',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR0hnWBXTbS6BwbHLOAUqiM6QSU-3QRco',
    appId: '1:691493604455:android:41191a4510b5f2d3f8d8c2',
    messagingSenderId: '691493604455',
    projectId: 'j2062-2dd01',
    databaseURL:
        'https://j2062-2dd01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'j2062-2dd01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4T1DUP3bkYFAnYORkq8HeolK--JBWUQ',
    appId: '1:691493604455:ios:68013949931c6a58f8d8c2',
    messagingSenderId: '691493604455',
    projectId: 'j2062-2dd01',
    databaseURL:
        'https://j2062-2dd01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'j2062-2dd01.firebasestorage.app',
    iosBundleId: 'com.example.hin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4T1DUP3bkYFAnYORkq8HeolK--JBWUQ',
    appId: '1:691493604455:ios:68013949931c6a58f8d8c2',
    messagingSenderId: '691493604455',
    projectId: 'j2062-2dd01',
    databaseURL:
        'https://j2062-2dd01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'j2062-2dd01.firebasestorage.app',
    iosBundleId: 'com.example.hin',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoi2z_zZGTE7Yb1hoUIEeyGhGUnLYUOl4',
    appId: '1:691493604455:web:909d790f3bd5cd7df8d8c2',
    messagingSenderId: '691493604455',
    projectId: 'j2062-2dd01',
    authDomain: 'j2062-2dd01.firebaseapp.com',
    databaseURL:
        'https://j2062-2dd01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'j2062-2dd01.firebasestorage.app',
    measurementId: 'G-CQP2V5CN1F',
  );
}
